// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfkhjldyhtnjnhdxdagf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ma2hqbGR5aHRuam5oZHhkYWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5ODEyMjYsImV4cCI6MjA4NDU1NzIyNn0.XoQFV2FKr34prSsatHuL0wi4fnS55gmpChkNTTw4ZmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});